version: 0.2
env:
  variables:
    CI: true
  parameter-store:
    DOCKERHUB_LOGIN: /dockerhub/login
    DOCKERHUB_PASS: /dockerhub/password
    BUNDLE_GEMS__GRAPHQL__PRO: /collect/graphql_creds
phases:
  install:
    runtime-versions:
      ruby: 3.2
  pre_build:
    commands:
      - aws_credentials=$(aws sts assume-role --role-arn $DEPLOY_ROLE_ARN --role-session-name apideploysession --output json)
      - export AWS_ACCESS_KEY_ID=$(echo $aws_credentials|jq '.Credentials.AccessKeyId'|tr -d '"')
      - export AWS_SECRET_ACCESS_KEY=$(echo $aws_credentials|jq '.Credentials.SecretAccessKey'|tr -d '"')
      - export AWS_SESSION_TOKEN=$(echo $aws_credentials|jq '.Credentials.SessionToken'|tr -d '"')
      - docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASS
  build:
    commands:
      - bundle lock --add-platform x86_64-linux
      - bundle add tcp-client
      - ./bin/deploy
cache:
  paths:
    - "vendor/bundle"
    - "node_modules/**/*"