version: 0.2
phases:
  pre_build:
    commands:
      - npm install -g aws-cdk
      - yarn install
  build:
    commands:
      - cdk deploy --all --require-approval never
cache:
  paths:
    - "node_modules/**/*"